# Generated by Django 2.2.8 on 2020-07-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('I', 'Instrument'), ('CC', 'CaseCover'), ('CS', 'Canes'), ('BS', 'Books')], default='I', max_length=2),
            preserve_default=False,
        ),
    ]
